version: '3'
services:
  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html"
    ports:
      - "7895:80"